# Generated by Django 5.0.4 on 2024-05-13 08:44

import line.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("line", "0003_alter_image_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="path",
            field=models.ImageField(
                help_text="The image's path from the website",
                upload_to=line.models.Image.get_upload_to,
            ),
        ),
    ]
